In [1]:
import pandas as pd
import numpy as np

C:\Users\Sneha\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
sem_data = 'Datesheet Generator.xlsx'
psc_data = 'PSC_List_10-3-2024 (1).xlsx'
holiday_data = 'holiday.xlsx'

In [3]:
df1 = pd.read_excel(sem_data)
psc_df = pd.read_excel(psc_data)
holiday_df = pd.read_excel(holiday_data)

In [4]:
df1

,S.No,Program,Semester,Course Code,Course Name,Course Type,No. of Students,L-T-P
0,1,B.Sc Chemistry,IV,CHH205B-T,PHYSICAL CHEMISTRY III,Core,9.0,3-1-0
1,2,B.Sc Chemistry,IV,CHH206B-T,INORGANIC CHEMISTRY III,Core,9.0,3-1-0
2,3,B.Sc Chemistry,IV,CHH207B-T,ORGANIC CHEMISTRY III,Core,9.0,0-0-3
3,4,B.Sc Chemistry,IV,CHH209B,INDUSTRIAL CHEMISTRY,Elective,9.0,3-1-0
4,5,B.Sc Chemistry,VI,CHH310B,Chemicals & Environment,Elective,5.0,3-1-0
...,...,...,...,...,...,...,...,...
478,479,B.Tech CSE - CSTI,VI,CSH313B-T,DATA WAREHOUSE & DATA MINING,Elective,30.0,3-0-2
479,480,B.Tech CSE - CSTI,VI,CSH314B,MACHINE LEARNING,Elective,30.0,3-0-2
480,481,B.Tech CSE - CSTI,VI,CSH306B-T,SYSTEM NETWORK & ADMINISTRATION,Elective,30.0,3-0-2
481,482,B.Tech CSE - CSTI,VI,LWS323/LWS325,CYBER LAW/\nLAW RELATING TO INTELLECTUAL PROPE...,Elective,30.0,2-0-0
482,483,B.Tech CSE - CSTI,VI,CDO332,PROFESSIONAL COMPETANCY ENHANCEMENT-IV,CDC,30.0,6-0-0

In [5]:
holiday_df

          Holiday      Date      Day
0    Republic Day 2024-01-26  Friday
1  Maha Shivratri 2024-03-08  Friday
2            Holi 2024-03-25  Monday
3     Id-Ul Zuha* 2024-06-17  Monday

In [6]:
psc_df

,Unnamed: 0,Student,Rollno,DOB,Type,Sub. Name,Sub. Code,Credit,Class,Semester,...,Exam Due In Head,Exam Due In Head.1,Exam Collection In Head,Exam Collection In Head.1,Outstanding Amount,Outstanding Amount.1,STATUS,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,1,Lakshay Bhardwaj,2K22CSUN06017,21/07/2003,Backlog,DATA STRUCTURES & ALGORITHMS,CSH103B-T,4.0,B.Tech R&AI,Sem 2,...,8000.0,26000.0,NaN,NaN,8000.0,26000.0,NOT PAID,NaN,NaN,NaN
1,2,Lalit Sharma,2K22CSUN06018,2004-04-09 00:00:00,Backlog,DATA STRUCTURES & ALGORITHMS,CSH103B-T,4.0,B.Tech R&AI,Sem 2,...,54000.0,77000.0,NaN,NaN,45800.0,68800.0,NOT PAID,NaN,NaN,NaN
2,3,Vulli Ajay Kumar,2K22CSUN06031,29/10/2004,Backlog,DATA STRUCTURES & ALGORITHMS,CSH103B-T,4.0,B.Tech R&AI,Sem 2,...,10000.0,14000.0,NaN,NaN,10000.0,14000.0,NOT PAID,NaN,NaN,NaN
3,4,Puthi Rishik Sai Kumar,2K22CSUN01115,17/09/2004,Backlog,DATA STRUCTURES & ALGORITHMS,CSH103B-T,4.0,BTech CSE,Sem 2,...,NaN,13000.0,NaN,13000.0,-2000.0,-2000.0,REGISTERED,NaN,NaN,NaN
4,5,Shivam Rajbhar,2K22CSUN06028,2004-09-09 00:00:00,Backlog,DATA STRUCTURES & ALGORITHMS,CSH103B-T,4.0,B.Tech R&AI,Sem 2,...,NaN,13000.0,NaN,9000.0,0.0,4000.0,NOT PAID,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,430,Deeksha Pandey,2K22CSUN01192,22/02/2004,Regular,AGILE SOFTWARE DEVELOPMENT (2023),CSH106B-T,4.0,B.Tech CSE CDFD (Xebia),Sem 2,...,6000.0,10000.0,6000.0,6000.0,0.0,4000.0,WILL NOT STUDY THIS SUBJECT,NaN,NaN,NaN
430,431,Aryan Sirohi,2K20CSUN01015,2003-05-02 00:00:00,Regular,COMPUTER GRAPHICS & MULTIMEDIA,CSH310B-T,4.0,BTech CSE,Sem 6,...,NaN,NaN,NaN,NaN,0.0,0.0,REGSIETERED,PAYMENT CLEARED,NaN,NaN
431,432,Mahesh Tanwar,2K20CSUN01065,26/09/2000,Regular,COMPUTER GRAPHICS & MULTIMEDIA,CSH310B-T,4.0,BTech CSE,Sem 6,...,NaN,17000.0,NaN,13000.0,0.0,4000.0,DUPLICATE ENTRY,NaN,NaN,NaN
432,433,Parag Mishra,2K20CSUN01074,24/04/2001,Regular,COMPUTER GRAPHICS & MULTIMEDIA,CSH310B-T,4.0,BTech CSE,Sem 6,...,NaN,NaN,200.0,200.0,0.0,-4000.0,REGISTERED,PAYMENT CLEARED,NaN,NaN
433,434,Maddimsetti Navadeep,2K20CSUN04035,2002-06-11 00:00:00,Regular,PROFESSIONAL COMPETENCY ENHANCEMENT-II,CDO202-P,0.5,B.Tech CSE AIML,Sem 4,...,NaN,NaN,NaN,NaN,0.0,0.0,REGISTERED,PAYMENT CLEARED,NaN,NaN

In [7]:
df1[['L', 'T', 'P']] = df1['L-T-P'].str.split('-', expand=True)
df1[['L', 'T', 'P']] = df1[['L', 'T', 'P']].apply(pd.to_numeric)
df1 = df1[(df1['L'] != 0)]

In [8]:
df1['Year'] = ''

# Define conditions and assign values to the "Year" column based on the "Semester" values
df1.loc[df1['Semester'].isin(['I', 'II']), 'Year'] = 1
df1.loc[df1['Semester'].isin(['III', 'IV']), 'Year'] = 2
df1.loc[df1['Semester'].isin(['V', 'VI']), 'Year'] = 3
df1.loc[df1['Semester'].isin(['VII', 'VIII']), 'Year'] = 4
df1.loc[df1['Semester'].isin(['IX', 'X']), 'Year'] = 5

C:\Users\Sneha\AppData\Local\Temp\ipykernel_9052\2606291672.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Year'] = ''

In [9]:
df1

,S.No,Program,Semester,Course Code,Course Name,Course Type,No. of Students,L-T-P,L,T,P,Year
0,1,B.Sc Chemistry,IV,CHH205B-T,PHYSICAL CHEMISTRY III,Core,9.0,3-1-0,3.0,1.0,0.0,2
1,2,B.Sc Chemistry,IV,CHH206B-T,INORGANIC CHEMISTRY III,Core,9.0,3-1-0,3.0,1.0,0.0,2
3,4,B.Sc Chemistry,IV,CHH209B,INDUSTRIAL CHEMISTRY,Elective,9.0,3-1-0,3.0,1.0,0.0,2
4,5,B.Sc Chemistry,VI,CHH310B,Chemicals & Environment,Elective,5.0,3-1-0,3.0,1.0,0.0,3
5,6,M.Sc Chemistry,II,CHH506B,Physical Chemistry-II,Core,6.0,4-0-0,4.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
478,479,B.Tech CSE - CSTI,VI,CSH313B-T,DATA WAREHOUSE & DATA MINING,Elective,30.0,3-0-2,3.0,0.0,2.0,3
479,480,B.Tech CSE - CSTI,VI,CSH314B,MACHINE LEARNING,Elective,30.0,3-0-2,3.0,0.0,2.0,3
480,481,B.Tech CSE - CSTI,VI,CSH306B-T,SYSTEM NETWORK & ADMINISTRATION,Elective,30.0,3-0-2,3.0,0.0,2.0,3
481,482,B.Tech CSE - CSTI,VI,LWS323/LWS325,CYBER LAW/\nLAW RELATING TO INTELLECTUAL PROPE...,Elective,30.0,2-0-0,2.0,0.0,0.0,3
482,483,B.Tech CSE - CSTI,VI,CDO332,PROFESSIONAL COMPETANCY ENHANCEMENT-IV,CDC,30.0,6-0-0,6.0,0.0,0.0,3

In [10]:
df1["Program"].unique()

array(['B.Sc Chemistry', 'M.Sc Chemistry', 'B.Sc Physics', 'M.Sc Physics',
       'B.Sc Maths', 'M.Sc Maths', 'BA B.ED', 'B.Sc B.ED', 'B.ED',
       'B.ED SPECIAL EDU.',
       'B.TECH IN ELECTRONICS AND COMMUNICATION ENGINEERING',
       'B.TECH IN ELECTRONICS AND COMMUNICATION ENGINEERING - VLSI',
       'M.Tech ECE', 'BA -LLB', 'BBA-LLB', 'B.COM LLB', 'LLB- 3 YEAR',
       'B.Tech ME (SMA)', 'B.Tech ME', 'M.Tech ME', 'BBA - EFB',
       'BBA - FAA', 'BBA - GHCM', 'BBA- GOM', 'BBA- BA', 'BBA - HCM',
       'BBA - GOM', 'BBA - BA', 'BBA - OM', 'MBA - BA', 'B.Tech CSE',
       'B.Tech CSE - AIML/CDFD/CSTI', 'B.Tech CSE - AIML',
       'B.Tech CSE - CDFD', 'B.Tech CSE - CSTI', 'B.Tech CSE - Robotics',
       'B.Tech CSE - AIML/CDA/CSTI', 'B.Tech CSE - CDA'], dtype=object)

In [11]:
course = df1["Course Name"].unique()

In [12]:
filtered_psc_df = psc_df[psc_df['Sub. Name'].isin(course)].copy()

psc_stu = pd.DataFrame()
psc_stu["Student"] = filtered_psc_df["Student"]
psc_stu["Rollno"] = filtered_psc_df["Rollno"]
psc_stu["Sub. Name"] = filtered_psc_df["Sub. Name"]
psc_stu["Semester"] = filtered_psc_df["Semester"]
psc_stu["Class"] = filtered_psc_df["Class"]
psc_stu["STATUS"] = filtered_psc_df["STATUS"]

psc_stu = psc_stu[psc_stu['STATUS'] == 'REGISTERED']

In [13]:
import datetime
c_year = int(str(datetime.datetime.now().year)[2:])
psc_stu['Current_year'] = c_year - psc_stu['Rollno'].str[2:4].fillna(0).astype(int)

In [14]:
psc_stu

,Student,Rollno,Sub. Name,Semester,Class,STATUS,Current_year
3,Puthi Rishik Sai Kumar,2K22CSUN01115,DATA STRUCTURES & ALGORITHMS,Sem 2,BTech CSE,REGISTERED,2
48,Mahesh Tanwar,2K20CSUN01065,APPLIED PSYCHOLOGY,Sem 6,BTech CSE,REGISTERED,4
49,Lakshay Bajaj,2K20CSUN01061,APPLIED PSYCHOLOGY,Sem 6,BTech CSE,REGISTERED,4
50,Nishchay Raj,2K22ECUN03008,APPLIED PSYCHOLOGY,Sem 2,B.Tech ECE VLSI D&V,REGISTERED,2
51,Sagar,2K20CSUN01091,APPLIED PSYCHOLOGY,Sem 6,BTech CSE,REGISTERED,4
52,Gandi Sai Swaroop,2K20CSUN01128,CLOUD COMPUTING,Sem 6,BTech CSE,REGISTERED,4
53,Lotti Uday Kiran Sai,2K20CSUN01063,CLOUD COMPUTING,Sem 6,BTech CSE,REGISTERED,4
55,Harsh Choudhary,2K20CSUN01042,CLOUD COMPUTING,Sem 6,BTech CSE,REGISTERED,4
89,Vibhor Sharma,2K22CSUN01126,DATA STRUCTURES & ALGORITHMS,Sem 2,BTech CSE,REGISTERED,2
92,Krishna Yadav,2K22CSUN06024,DATA STRUCTURES & ALGORITHMS,Sem 2,B.Tech R&AI,REGISTERED,2
118,Puthi Rishik Sai Kumar,2K22CSUN01115,CHEMISTRY,Sem 2,BTech CSE,REGISTERED,2
119,Anshul Semwal,2K22CSUN01005,CHEMISTRY,Sem 2,BTech CSE,REGISTERED,2
136,Lakshay Bajaj,2K20CSUN01061,COMPUTER GRAPHICS & MULTIMEDIA,Sem 6,BTech CSE,REGISTERED,4
137,Sagar,2K20CSUN01091,COMPUTER GRAPHICS & MULTIMEDIA,Sem 6,BTech CSE,REGISTERED,4
149,Kotakommula Sai Pavan Kalyan,2K20CSUN04031,OPERATING SYSTEM,Sem 4,B.Tech CSE AIML,REGISTERED,4
150,Aseem,2K21CSUN04007,OPERATING SYSTEM,Sem 3,B.Tech CSE AIML,REGISTERED,3
153,Maddimsetti Navadeep,2K20CSUN04035,OPERATING SYSTEM,Sem 4,B.Tech CSE AIML,REGISTERED,4
163,Anuj Chaher,2K22MEUN03002,PROFESSIONAL ENGLISH,Sem 2,SMA,REGISTERED,2
164,Ayush Sharma,2K22CSUN01164,PROFESSIONAL ENGLISH,Sem 2,B.Tech CSE AIML,REGISTERED,2
179,Enumula Saketh Kumar,2K21CSUN04047,PYTHON PROGRAMMING,Sem 2,B.Tech CSE AIML,REGISTERED,3
202,Kotakommula Sai Pavan Kalyan,2K20CSUN04031,BIOLOGY,Sem 7,B.Tech CSE AIML,REGISTERED,4
208,Potlapally Sai Teja,2K20CSUN04040,DIGITAL MARKETING,Sem 5,B.Tech CSE AIML,REGISTERED,4
209,Arjun Vats,2K21CSUN04006,FRENCH-II,Sem 4,B.Tech CSE AIML,REGISTERED,3
214,Gadi Teja Siva Sankar Guru Sai,2K20CSUN04020,THEORY OF AUTOMATA & COMPILER DESIGN,Sem 7,B.Tech CSE AIML,REGISTERED,4
215,Vudari Dhamaruka Sivasai,2K20CSUN04055,THEORY OF AUTOMATA & COMPILER DESIGN,Sem 7,B.Tech CSE AIML,REGISTERED,4
216,Ireddi Sai Krishna,2K20CSUN04025,THEORY OF AUTOMATA & COMPILER DESIGN,Sem 7,B.Tech CSE AIML,REGISTERED,4
225,Aditya Sharma,2K21CSUN01005,PROFESSIONAL COMPETANCY ENHANCEMENT-II,Sem 4,BTech CSE,REGISTERED,3
254,Tushar Joshi,2K22CSUN01155,CHEMISTRY-1,Sem 1,B.Tech CSE AIML,REGISTERED,2
255,Mareti Ganesh Ram,2K22CSUN01239,CHEMISTRY-1,Sem 1,B.Tech CSE CSTI,REGISTERED,2
257,Ashna Jain,2K22CSUN01131,QUANTUM MECHANICS FOR ENGINEER,Sem 2,B.Tech CSE AIML,REGISTERED,2
273,Enumula Saketh Kumar,2K21CSUN04047,PROFESSIONAL COMMUNICATION-II,Sem 2,B.Tech CSE AIML,REGISTERED,3
278,Rahil Singh Dalal,2K21CSUN01138,PROFESSIONAL COMPETENCY ENHANCEMENT-II,Sem 4,BTech CSE,REGISTERED,3
280,Gopal Sharma,2K21CSUN01115,PROFESSIONAL COMPETENCY ENHANCEMENT-II,Sem 4,BTech CSE,REGISTERED,3
298,Karan Khanduja,2K20MEUN03004,PROFESSIONAL COMPETANCY ENHANCEMENT-IV,Sem 6,SMA,REGISTERED,4
301,Karan Khanduja,2K20MEUN03004,GERMAN-II,Sem 4,SMA,REGISTERED,4
309,Anuj,2K22CSUN01088,DATA STRUCTURES & ALGORITHMS,Sem 2,BTech CSE,REGISTERED,2
310,Prateek Tyagi,2K21CSUN04057,DATA STRUCTURES & ALGORITHMS,Sem 3,B.Tech CSE AIML,REGISTERED,3
311,Krishna Yadav,2K22CSUN06013,DATA STRUCTURES & ALGORITHMS,Sem 2,B.Tech R&AI,REGISTERED,2
314,Anup Attri,2K22CSUN01054,DATA STRUCTURES & ALGORITHMS,Sem 2,BTech CSE,REGISTERED,2
315,Nakul,2K22CSUN01073,DATA STRUCTURES & ALGORITHMS,Sem 2,BTech CSE,REGISTERED,2
335,Pushpender,2K19CSUN01047,COMPUTER NETWORKS,Sem 5,BTech CSE,REGISTERED,5
340,Ayush Sharma,2K22CSUN01164,PROFESSIONAL ENGLISH,Sem 2,B.Tech CSE AIML,REGISTERED,2
347,Mohd Shahid Raza,2K21CSUL04002,INDIAN CONSTITUTION,Sem 4,B.Tech CSE AIML,REGISTERED,3
377,Sanidhya Tiwari,2K21CSUN01091,DISCRETE MATHEMATICS,Sem 4,BTech CSE,REGISTERED,3
381,Lotti Uday Kiran Sai,2K20CSUN01063,FRENCH-II,Sem 4,BTech CSE,REGISTERED,4
421,Navneet,2K21CSUN03009,CALCULUS & LINEAR ALGEBRA,Sem 2,B.Tech CSE CDA,REGISTERED,3
432,Parag Mishra,2K20CSUN01074,COMPUTER GRAPHICS & MULTIMEDIA,Sem 6,BTech CSE,REGISTERED,4
433,Maddimsetti Navadeep,2K20CSUN04035,PROFESSIONAL COMPETENCY ENHANCEMENT-II,Sem 4,B.Tech CSE AIML,REGISTERED,4

In [15]:
sub_name_counts = psc_stu.groupby(["Sub. Name", "Class"]).size()
print(sub_name_counts)

Sub. Name                               Class
APPLIED PSYCHOLOGY                      B.Tech ECE VLSI D&V    1
                                        BTech CSE              3
BIOLOGY                                 B.Tech CSE AIML        1
CALCULUS & LINEAR ALGEBRA               B.Tech CSE CDA         1
CHEMISTRY                               BTech CSE              2
CHEMISTRY-1                             B.Tech CSE AIML        1
                                        B.Tech CSE CSTI        1
CLOUD COMPUTING                         BTech CSE              3
COMPUTER GRAPHICS & MULTIMEDIA          BTech CSE              3
COMPUTER NETWORKS                       BTech CSE              1
DATA STRUCTURES & ALGORITHMS            B.Tech CSE AIML        1
                                        B.Tech R&AI            2
                                        BTech CSE              5
DIGITAL MARKETING                       B.Tech CSE AIML        1
DISCRETE MATHEMATICS                    BTech CSE              1
FRENCH-II                               B.Tech CSE AIML        1
                                        BTech CSE              1
GERMAN-II                               SMA                    1
INDIAN CONSTITUTION                     B.Tech CSE AIML        1
OPERATING SYSTEM                        B.Tech CSE AIML        3
PROFESSIONAL COMMUNICATION-II           B.Tech CSE AIML        1
PROFESSIONAL COMPETANCY ENHANCEMENT-II  BTech CSE              1
PROFESSIONAL COMPETANCY ENHANCEMENT-IV  SMA                    1
PROFESSIONAL COMPETENCY ENHANCEMENT-II  B.Tech CSE AIML        1
                                        BTech CSE              2
PROFESSIONAL ENGLISH                    B.Tech CSE AIML        2
                                        SMA                    1
PYTHON PROGRAMMING                      B.Tech CSE AIML        1
QUANTUM MECHANICS FOR ENGINEER          B.Tech CSE AIML        1
THEORY OF AUTOMATA & COMPILER DESIGN    B.Tech CSE AIML        3
dtype: int64

In [16]:
# Calculate the number of students for each subject in PSC data
psc_students_count = psc_stu["Sub. Name"].value_counts()

# Iterate through each subject in the PSC data
for subject, count in psc_students_count.items():
    # Check if the subject exists in df1
    if subject in df1['Course Name'].values:
        # Add the number of students from PSC data to the corresponding subject in df1
        df1.loc[df1['Course Name'] == subject, 'No. of Students'] += count
    else:
        print(f"Subject {subject} from PSC data not found in df1.")

In [17]:
# Iterate through each row in the DataFrame containing student data
for index, row in psc_stu.iterrows():
    # Extract relevant information from the row
    subject = row['Sub. Name']
    current_year = row['Current_year']
    
    # Check if the subject exists in psc_df
    if subject in psc_df['Sub. Name'].values:
        # If the subject is found, add the current_year to the corresponding row in df1
        df1.loc[df1['Course Name'] == subject, 'psc_year'] = current_year
    else:
        # If the subject is not found, add {0} to indicate that the subject is not present in psc_df
        df1.loc[df1['Course Name'] == subject, 'psc_year'] = 0

C:\Users\Sneha\AppData\Local\Temp\ipykernel_9052\2674797414.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.loc[df1['Course Name'] == subject, 'psc_year'] = current_year

In [18]:
df1

,S.No,Program,Semester,Course Code,Course Name,Course Type,No. of Students,L-T-P,L,T,P,Year,psc_year
0,1,B.Sc Chemistry,IV,CHH205B-T,PHYSICAL CHEMISTRY III,Core,9.0,3-1-0,3.0,1.0,0.0,2,NaN
1,2,B.Sc Chemistry,IV,CHH206B-T,INORGANIC CHEMISTRY III,Core,9.0,3-1-0,3.0,1.0,0.0,2,NaN
3,4,B.Sc Chemistry,IV,CHH209B,INDUSTRIAL CHEMISTRY,Elective,9.0,3-1-0,3.0,1.0,0.0,2,NaN
4,5,B.Sc Chemistry,VI,CHH310B,Chemicals & Environment,Elective,5.0,3-1-0,3.0,1.0,0.0,3,NaN
5,6,M.Sc Chemistry,II,CHH506B,Physical Chemistry-II,Core,6.0,4-0-0,4.0,0.0,0.0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,479,B.Tech CSE - CSTI,VI,CSH313B-T,DATA WAREHOUSE & DATA MINING,Elective,30.0,3-0-2,3.0,0.0,2.0,3,NaN
479,480,B.Tech CSE - CSTI,VI,CSH314B,MACHINE LEARNING,Elective,30.0,3-0-2,3.0,0.0,2.0,3,NaN
480,481,B.Tech CSE - CSTI,VI,CSH306B-T,SYSTEM NETWORK & ADMINISTRATION,Elective,30.0,3-0-2,3.0,0.0,2.0,3,NaN
481,482,B.Tech CSE - CSTI,VI,LWS323/LWS325,CYBER LAW/\nLAW RELATING TO INTELLECTUAL PROPE...,Elective,30.0,2-0-0,2.0,0.0,0.0,3,NaN
482,483,B.Tech CSE - CSTI,VI,CDO332,PROFESSIONAL COMPETANCY ENHANCEMENT-IV,CDC,31.0,6-0-0,6.0,0.0,0.0,3,4.0

In [19]:
final_df = pd.DataFrame()

In [20]:
final_df["Program"] = df1["Program"]
final_df["Semester"]= df1["Semester"]
final_df["Course_Name"]= df1["Course Name"]
final_df["Course_Code"]= df1["Course Code"]
final_df["Course_Type"]= df1["Course Type"]
final_df["Total students"]= df1["No. of Students"]

In [28]:
import pandas as pd
import numpy as np

# Define start and end dates
start_date = '2024-03-11'
end_date = '2024-04-28'

# Create date range and select weekdays
date_range = pd.date_range(start=start_date, end=end_date)
weekdays_range = date_range[date_range.dayofweek < 5]

# Define time slots based on term
term = "end-term"  # or "mid-term"
if term == "mid-term":
    time_slots = [
        '9:00 - 10:30', 
        '11:30 - 13:00', 
        '14:00 - 15:30'
    ]
elif term == "end-term":
    time_slots = [
        '9:00 - 12:30', 
        '13:00 - 15:30'
    ]

# Define semester mapping
semester_mapping = {
    "I": 1,
    "II": 2,
    "III": 3,
    "IV": 4,
    # Add more mappings as needed
}

# Initialize variables
date_index = 0  
prev_program_semester = None  
last_time_slot = None  # Track the last assigned time slot
last_date = {}

# Iterate over rows in df1
for i, row in df1.iterrows():
    if pd.isna(row["Course Name"]):  
        final_df.at[i, 'Date'] = np.nan  
        date_index = 0  
    else:
        program_semester = (row["Program"], semester_mapping.get(row["Semester"], None))  # Convert semester name to integer
        
        if program_semester[1] is not None:
            if program_semester != prev_program_semester:
                date_index = 0  
                prev_program_semester = program_semester
                semester_index = program_semester[1] - 1  # Adjust time slot index based on semester
                time_slot_index = semester_index % len(time_slots)
                last_time_slot = None  # Reset last_time_slot when program/semester changes

            if program_semester in last_date:
                last_assigned_date = last_date[program_semester] + pd.Timedelta(days=2) 
            else:
                last_assigned_date = pd.Timestamp(weekdays_range[0])  

            while True:
                if date_index >= len(weekdays_range):
                    # Reset date index if all dates are used
                    date_index = 0

                if weekdays_range[date_index].dayofweek < 5:
                    current_date = pd.Timestamp(weekdays_range[date_index].date())  
                    if current_date >= last_assigned_date:
                        final_df.at[i, 'Date'] = current_date  
                        last_date[program_semester] = current_date 

                        # Assign the appropriate time slot based on semester
                        final_df.at[i, 'Time Slot'] = time_slots[time_slot_index]
                        last_time_slot = final_df.at[i, 'Time Slot']

                        # Increment time slot index for the next iteration
                        time_slot_index = (time_slot_index + 1) % len(time_slots)

                        date_index += 1  
                        break
                    else:
                        date_index += 1  
                else:
                    date_index += 1

In [29]:
final_df

,Program,Semester,Course_Name,Course_Code,Course_Type,Total students,Date,Time Slot
0,B.Sc Chemistry,IV,PHYSICAL CHEMISTRY III,CHH205B-T,Core,9.0,2024-03-11,13:00 - 15:30
1,B.Sc Chemistry,IV,INORGANIC CHEMISTRY III,CHH206B-T,Core,9.0,2024-03-13,9:00 - 12:30
3,B.Sc Chemistry,IV,INDUSTRIAL CHEMISTRY,CHH209B,Elective,9.0,2024-03-15,13:00 - 15:30
4,B.Sc Chemistry,VI,Chemicals & Environment,CHH310B,Elective,5.0,NaT,NaN
5,M.Sc Chemistry,II,Physical Chemistry-II,CHH506B,Core,6.0,2024-03-11,13:00 - 15:30
...,...,...,...,...,...,...,...,...
478,B.Tech CSE - CSTI,VI,DATA WAREHOUSE & DATA MINING,CSH313B-T,Elective,30.0,NaT,NaN
479,B.Tech CSE - CSTI,VI,MACHINE LEARNING,CSH314B,Elective,30.0,NaT,NaN
480,B.Tech CSE - CSTI,VI,SYSTEM NETWORK & ADMINISTRATION,CSH306B-T,Elective,30.0,NaT,NaN
481,B.Tech CSE - CSTI,VI,CYBER LAW/\nLAW RELATING TO INTELLECTUAL PROPE...,LWS323/LWS325,Elective,30.0,NaT,NaN
482,B.Tech CSE - CSTI,VI,PROFESSIONAL COMPETANCY ENHANCEMENT-IV,CDO332,CDC,31.0,NaT,NaN

In [56]:
# Group the dataframe by 'Date' and 'Time Slot' and sum the 'Total students' column
total_students_count = final_df.groupby(['Date', 'Time Slot'])['Total students'].sum().reset_index()

print(total_students_count)

         Date     Time Slot  Total students
0  2024-03-11  9:00 - 12:30          2536.0
1  2024-03-13  9:00 - 12:30          2164.0
2  2024-03-15  9:00 - 12:30          2182.0
3  2024-03-18  9:00 - 12:30          2210.0
4  2024-03-20  9:00 - 12:30          2092.0
5  2024-03-22  9:00 - 12:30          1829.0
6  2024-03-25  9:00 - 12:30          1306.0
7  2024-03-27  9:00 - 12:30           480.0
8  2024-03-29  9:00 - 12:30           438.0
9  2024-04-01  9:00 - 12:30           298.0
10 2024-04-03  9:00 - 12:30           234.0
11 2024-04-05  9:00 - 12:30           222.0
12 2024-04-08  9:00 - 12:30           169.0
13 2024-04-10  9:00 - 12:30           171.0
14 2024-04-12  9:00 - 12:30           173.0
15 2024-04-15  9:00 - 12:30            12.0
16 2024-04-17  9:00 - 12:30            12.0

In [62]:
# Group the dataframe by 'Date' and 'Time Slot' and sum the 'Total students' column
total_students_count = final_df.groupby(['Date', 'Time Slot'])['Total students'].sum().reset_index()

# Iterate through each group
for date_slot, group_df in final_df.groupby(['Date', 'Time Slot']):
    date, time_slot = date_slot
    total_students = total_students_count.loc[(total_students_count['Date'] == date) & (total_students_count['Time Slot'] == time_slot), 'Total students'].iloc[0]
    if total_students > 800:
        # Assign a different time slot for subjects on the same date
        new_time_slot_index = time_slots.index(time_slot) + 1  # Increment time slot index
        if new_time_slot_index >= len(time_slots):
            new_time_slot_index = 0  # Wrap around to the first time slot if the last is reached
        new_time_slot = time_slots[new_time_slot_index]

        # Update the time slot for subjects on the same date and time slot
        final_df.loc[(final_df['Date'] == date) & (final_df['Time Slot'] == time_slot), 'Time Slot'] = new_time_slot

In [63]:
total_students_count = final_df.groupby(['Date', 'Time Slot'])['Total students'].sum().reset_index()

print(total_students_count)

         Date      Time Slot  Total students
0  2024-03-11  13:00 - 15:30          2536.0
1  2024-03-13   9:00 - 12:30          2164.0
2  2024-03-15  13:00 - 15:30          2182.0
3  2024-03-18   9:00 - 12:30          2210.0
4  2024-03-20  13:00 - 15:30          2092.0
5  2024-03-22   9:00 - 12:30          1829.0
6  2024-03-25  13:00 - 15:30          1306.0
7  2024-03-27   9:00 - 12:30           480.0
8  2024-03-29   9:00 - 12:30           438.0
9  2024-04-01   9:00 - 12:30           298.0
10 2024-04-03   9:00 - 12:30           234.0
11 2024-04-05   9:00 - 12:30           222.0
12 2024-04-08   9:00 - 12:30           169.0
13 2024-04-10   9:00 - 12:30           171.0
14 2024-04-12   9:00 - 12:30           173.0
15 2024-04-15   9:00 - 12:30            12.0
16 2024-04-17   9:00 - 12:30            12.0

In [29]:
# Iterate through each row in the PSC DataFrame
for index, row in psc_stu.iterrows():
    sub_name = row['Sub. Name']
    program = row['Class']
    no_of_students = 1  # Assuming each row represents one student

    # Check if the program and course name exist in df1
    if ((df1['Program'] == program) & (df1['Course Name'] == sub_name)).any():
        # Add the number of students from PSC data to the corresponding subject in df1
        df1.loc[(df1['Program'] == program) & (df1['Course Name'] == sub_name), 'No. of Students'] += no_of_students
    else:
        print(f"No corresponding subject found in df1 for Program: {program} and Course Name: {sub_name}.")

# Display the updated DataFrame df1
df1

No corresponding subject found in df1 for Program: BTech CSE and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: APPLIED PSYCHOLOGY.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: APPLIED PSYCHOLOGY.
No corresponding subject found in df1 for Program: B.Tech ECE VLSI D&V and Course Name: APPLIED PSYCHOLOGY.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: APPLIED PSYCHOLOGY.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: CLOUD COMPUTING.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: CLOUD COMPUTING.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: CLOUD COMPUTING.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: B.Tech R&AI and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: CHEMISTRY.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: CHEMISTRY.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: COMPUTER GRAPHICS & MULTIMEDIA.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: COMPUTER GRAPHICS & MULTIMEDIA.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: OPERATING SYSTEM.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: OPERATING SYSTEM.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: OPERATING SYSTEM.
No corresponding subject found in df1 for Program: SMA and Course Name: PROFESSIONAL ENGLISH.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: PROFESSIONAL ENGLISH.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: PYTHON PROGRAMMING.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: BIOLOGY.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: DIGITAL MARKETING.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: FRENCH-II.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: THEORY OF AUTOMATA & COMPILER DESIGN.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: THEORY OF AUTOMATA & COMPILER DESIGN.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: THEORY OF AUTOMATA & COMPILER DESIGN.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: PROFESSIONAL COMPETANCY ENHANCEMENT-II.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: CHEMISTRY-1.
No corresponding subject found in df1 for Program: B.Tech CSE CSTI and Course Name: CHEMISTRY-1.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: QUANTUM MECHANICS FOR ENGINEER.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: PROFESSIONAL COMMUNICATION-II.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: PROFESSIONAL COMPETENCY ENHANCEMENT-II.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: PROFESSIONAL COMPETENCY ENHANCEMENT-II.
No corresponding subject found in df1 for Program: SMA and Course Name: PROFESSIONAL COMPETANCY ENHANCEMENT-IV.
No corresponding subject found in df1 for Program: SMA and Course Name: GERMAN-II.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: B.Tech R&AI and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: DATA STRUCTURES & ALGORITHMS.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: COMPUTER NETWORKS.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: PROFESSIONAL ENGLISH.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: INDIAN CONSTITUTION.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: DISCRETE MATHEMATICS.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: FRENCH-II.
No corresponding subject found in df1 for Program: B.Tech CSE CDA and Course Name: CALCULUS & LINEAR ALGEBRA.
No corresponding subject found in df1 for Program: BTech CSE and Course Name: COMPUTER GRAPHICS & MULTIMEDIA.
No corresponding subject found in df1 for Program: B.Tech CSE AIML and Course Name: PROFESSIONAL COMPETENCY ENHANCEMENT-II.

,S.No,Program,Semester,Course Code,Course Name,Course Type,No. of Students,L-T-P,L,T,P,Year
0,1,B.Sc Chemistry,IV,CHH205B-T,PHYSICAL CHEMISTRY III,Core,9.0,3-1-0,3.0,1.0,0.0,2
1,2,B.Sc Chemistry,IV,CHH206B-T,INORGANIC CHEMISTRY III,Core,9.0,3-1-0,3.0,1.0,0.0,2
3,4,B.Sc Chemistry,IV,CHH209B,INDUSTRIAL CHEMISTRY,Elective,9.0,3-1-0,3.0,1.0,0.0,2
4,5,B.Sc Chemistry,VI,CHH310B,Chemicals & Environment,Elective,5.0,3-1-0,3.0,1.0,0.0,3
5,6,M.Sc Chemistry,II,CHH506B,Physical Chemistry-II,Core,6.0,4-0-0,4.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
478,479,B.Tech CSE - CSTI,VI,CSH313B-T,DATA WAREHOUSE & DATA MINING,Elective,30.0,3-0-2,3.0,0.0,2.0,3
479,480,B.Tech CSE - CSTI,VI,CSH314B,MACHINE LEARNING,Elective,30.0,3-0-2,3.0,0.0,2.0,3
480,481,B.Tech CSE - CSTI,VI,CSH306B-T,SYSTEM NETWORK & ADMINISTRATION,Elective,30.0,3-0-2,3.0,0.0,2.0,3
481,482,B.Tech CSE - CSTI,VI,LWS323/LWS325,CYBER LAW/\nLAW RELATING TO INTELLECTUAL PROPE...,Elective,30.0,2-0-0,2.0,0.0,0.0,3
482,483,B.Tech CSE - CSTI,VI,CDO332,PROFESSIONAL COMPETANCY ENHANCEMENT-IV,CDC,32.0,6-0-0,6.0,0.0,0.0,3